# Generated by Django 3.2.9 on 2021-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adelantosalario',
            fields=[
                ('idadelanto', models.AutoField(db_column='IdAdelanto', primary_key=True, serialize=False)),
                ('monto', models.FloatField(db_column='Monto')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('aprobadopor', models.CharField(db_collation='utf8_general_ci', db_column='AprobadoPor', max_length=25)),
                ('conceptode', models.TextField(db_column='ConceptoDe')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'adelantosalario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Areaempresa',
            fields=[
                ('codarea', models.CharField(db_collation='utf8_general_ci', db_column='CodArea', max_length=8, primary_key=True, serialize=False)),
                ('nombrearea', models.CharField(db_collation='utf8_general_ci', db_column='NombreArea', max_length=25)),
                ('nivelarea', models.IntegerField(db_column='NivelArea')),
                ('areasuperior', models.IntegerField(db_column='AreaSuperior')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'areaempresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('codigo_au', models.AutoField(db_column='CODIGO_AU', primary_key=True, serialize=False)),
                ('codusuario_au', models.CharField(db_column='CodUSUARIO_AU', max_length=20)),
                ('tabla', models.CharField(db_column='TABLA', max_length=20)),
                ('accion', models.CharField(db_column='ACCION', max_length=20)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('fecha_hora', models.DateTimeField(db_column='FECHA_HORA')),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campoinstrumento',
            fields=[
                ('idcampoinstrumento', models.AutoField(db_column='IdCampoInstrumento', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('porcentaje', models.FloatField(blank=True, db_column='Porcentaje', null=True)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'campoinstrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codcargo', models.CharField(db_collation='utf8_general_ci', db_column='Codcargo', max_length=8, primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(db_collation='utf8_general_ci', db_column='NombreCargo', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargosalario',
            fields=[
                ('idcargosalario', models.AutoField(db_column='IdCargoSalario', primary_key=True, serialize=False)),
                ('salario', models.FloatField(db_column='Salario')),
                ('aprobadopor', models.CharField(db_collation='utf8_general_ci', db_column='AprobadoPor', max_length=25)),
                ('fechaaprobacion', models.DateField(db_column='FechaAprobacion')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cargosalario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casadeestudio',
            fields=[
                ('idcasaestudio', models.AutoField(db_column='IdCasaEstudio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('fechafund', models.DateField(db_column='FechaFund')),
                ('nombrecorto', models.CharField(db_collation='utf8_general_ci', db_column='NombreCorto', max_length=10)),
                ('descripcion', models.CharField(db_collation='utf8_general_ci', db_column='Descripcion', max_length=250)),
            ],
            options={
                'db_table': 'casadeestudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catciudad',
            fields=[
                ('idciudad', models.IntegerField(db_column='IdCiudad', primary_key=True, serialize=False)),
                ('nombreciudad', models.CharField(db_collation='utf8_general_ci', db_column='NombreCiudad', max_length=100)),
            ],
            options={
                'db_table': 'catciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatFechasession',
            fields=[
                ('idcat_fecho', models.AutoField(db_column='idCat_Fecho', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'cat_fechasession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatFunciones',
            fields=[
                ('idfuncion', models.AutoField(db_column='IdFuncion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_funciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatHabilidades',
            fields=[
                ('idhabilidades', models.AutoField(db_column='IdHabilidades', primary_key=True, serialize=False)),
                ('nombrehabilidad', models.CharField(db_collation='utf8_general_ci', db_column='NombreHabilidad', max_length=25)),
            ],
            options={
                'db_table': 'cat_habilidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPadecimientos',
            fields=[
                ('codenfermedad', models.CharField(db_collation='utf8_general_ci', db_column='CodEnfermedad', max_length=8, primary_key=True, serialize=False)),
                ('nombrepadecimiento', models.CharField(db_collation='utf8_general_ci', db_column='NombrePadecimiento', max_length=25)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('fechaingreso', models.DateTimeField(db_column='FechaIngreso')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_padecimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catprueba',
            fields=[
                ('codprueba', models.CharField(db_collation='utf8_general_ci', db_column='CodPrueba', max_length=8, primary_key=True, serialize=False)),
                ('tituloprueba', models.CharField(db_collation='utf8_general_ci', db_column='TituloPrueba', max_length=25)),
                ('fechaemision', models.DateField(db_column='FechaEmision')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'catprueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPublicidad',
            fields=[
                ('idpublicidad', models.AutoField(db_column='IdPublicidad', primary_key=True, serialize=False)),
                ('nombrepublicidad', models.CharField(db_collation='utf8_general_ci', db_column='NombrePublicidad', max_length=25)),
                ('abreviacion', models.CharField(db_collation='utf8_general_ci', db_column='Abreviacion', max_length=5)),
            ],
            options={
                'db_table': 'cat_publicidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatRedessociales',
            fields=[
                ('idredes', models.AutoField(db_column='IdRedes', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_redessociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatRequerimientos',
            fields=[
                ('idrequerimiento', models.AutoField(db_column='IdRequerimiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_requerimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatRols',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=50)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_rols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipoestudio',
            fields=[
                ('idtipoestudio', models.AutoField(db_column='IdTipoEstudio', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_collation='utf8_general_ci', db_column='NombreTipo', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_tipoestudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiponomina',
            fields=[
                ('idtiponomina', models.AutoField(db_column='IdTipoNomina', primary_key=True, serialize=False)),
                ('tiponomina', models.CharField(db_collation='utf8_general_ci', db_column='TipoNomina', max_length=50)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'cat_tiponomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipopadecimiento',
            fields=[
                ('codtipopadecimiento', models.CharField(db_collation='utf8_general_ci', db_column='CodTipoPadecimiento', max_length=8, primary_key=True, serialize=False)),
                ('nombretipopadecimiento', models.CharField(db_collation='utf8_general_ci', db_column='NombreTipoPadecimiento', max_length=50)),
            ],
            options={
                'db_table': 'cat_tipopadecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipovacante',
            fields=[
                ('idtipovacante', models.AutoField(db_column='IdTipoVacante', primary_key=True, serialize=False)),
                ('tipovacante', models.CharField(db_collation='utf8_general_ci', db_column='TipoVacante', max_length=25)),
            ],
            options={
                'db_table': 'cat_tipovacante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clausulascontrato',
            fields=[
                ('idclausulacontrato', models.AutoField(db_column='IdClausulaContrato', primary_key=True, serialize=False)),
                ('numclausula', models.IntegerField(db_column='NumClausula')),
                ('clausula', models.TextField(db_column='Clausula')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'clausulascontrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companiatelefonica',
            fields=[
                ('codcompania', models.CharField(db_collation='utf8_general_ci', db_column='CodCompania', max_length=10, primary_key=True, serialize=False)),
                ('nombrecompania', models.CharField(db_collation='utf8_general_ci', db_column='NombreCompania', max_length=25)),
            ],
            options={
                'db_table': 'companiatelefonica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conexiones',
            fields=[
                ('idconecinte', models.AutoField(db_column='idConecInte', primary_key=True, serialize=False)),
                ('sessionopen', models.DateTimeField(db_column='SessionOpen')),
                ('sessionclose', models.DateTimeField(db_column='SessionClose')),
            ],
            options={
                'db_table': 'conexiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('codcontrato', models.CharField(db_collation='utf8_general_ci', db_column='CodContrato', max_length=12, primary_key=True, serialize=False)),
                ('nombrecontrato', models.CharField(db_collation='utf8_general_ci', db_column='NombreContrato', max_length=20)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correopersona',
            fields=[
                ('idcorreopersonal', models.AutoField(db_column='IdCorreoPersonal', primary_key=True, serialize=False)),
                ('correo', models.CharField(db_collation='utf8_general_ci', db_column='Correo', max_length=100)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'correopersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependientes',
            fields=[
                ('idfamiliar', models.AutoField(db_column='IdFamiliar', primary_key=True, serialize=False)),
                ('difunto', models.TextField(db_column='Difunto')),
                ('esbeneficiario', models.TextField(db_column='EsBeneficiario')),
                ('porcentaje', models.FloatField(db_column='Porcentaje')),
            ],
            options={
                'db_table': 'dependientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descripcionparentesco',
            fields=[
                ('iddescripcion', models.AutoField(db_column='IdDescripcion', primary_key=True, serialize=False)),
                ('tituloparentesco', models.CharField(db_collation='utf8_general_ci', db_column='TituloParentesco', max_length=25)),
                ('detalle', models.TextField(db_column='Detalle')),
            ],
            options={
                'db_table': 'descripcionparentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalletablaprogresiva',
            fields=[
                ('iddetalleir', models.AutoField(db_column='IdDetalleIr', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=1)),
                ('desde', models.FloatField(db_column='Desde')),
                ('hasta', models.FloatField(db_column='Hasta')),
                ('impuestobase', models.IntegerField(db_column='ImpuestoBase')),
                ('porcentajeaplicable', models.FloatField(db_column='PorcentajeAplicable')),
                ('sobreexceso', models.IntegerField(db_column='SobreExceso')),
            ],
            options={
                'db_table': 'detalletablaprogresiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapago', models.DateTimeField(db_column='FechaPago')),
                ('diaslaborados', models.FloatField(db_column='DiasLaborados')),
                ('salarioporhora', models.FloatField(db_column='SalarioPorHora')),
                ('deduccionpermiso', models.FloatField(db_column='DeduccionPermiso')),
                ('septimo', models.FloatField(db_column='Septimo')),
                ('vacacionespagadasq', models.IntegerField(db_column='VacacionesPagadasQ')),
                ('vacacionespagadasr', models.FloatField(db_column='VacacionesPagadasR')),
                ('llegadastardiasq', models.IntegerField(db_column='LlegadasTardiasQ')),
                ('llegadastardiasr', models.FloatField(db_column='LlegadasTardiasR')),
                ('anticiposq', models.IntegerField(db_column='AnticiposQ')),
                ('anticiposr', models.FloatField(db_column='AnticiposR')),
                ('horasextraq', models.IntegerField(db_column='HorasExtraQ')),
                ('horasextrasr', models.FloatField(db_column='HorasExtrasR')),
                ('incentivor', models.FloatField(db_column='IncentivoR')),
                ('salariobruto', models.FloatField(db_column='SalarioBruto')),
                ('insslaboral', models.FloatField(db_column='INSSLaboral')),
                ('irdeducido', models.FloatField(db_column='IRDeducido')),
                ('insspatronal', models.FloatField(db_column='INSSPatronal')),
                ('inatec', models.FloatField(db_column='Inatec')),
                ('antiguedades', models.FloatField(db_column='Antiguedades')),
                ('salarioneto', models.FloatField(db_column='SalarioNeto')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'det_nomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccionpersona',
            fields=[
                ('iddireccionpersona', models.AutoField(db_column='IdDireccionPersona', primary_key=True, serialize=False)),
                ('direccion', models.CharField(db_collation='utf8_general_ci', db_column='Direccion', max_length=100)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'direccionpersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codempleado', models.CharField(db_collation='utf8_general_ci', db_column='CodEmpleado', max_length=8, primary_key=True, serialize=False)),
                ('codinss', models.CharField(db_collation='utf8_general_ci', db_column='CodINSS', max_length=15)),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafinal', models.DateField(db_column='FechaFinal')),
                ('anoslaborando', models.FloatField(db_column='AnosLaborando')),
                ('codcontrato', models.CharField(db_collation='utf8_general_ci', db_column='CodContrato', max_length=8)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleadoformato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(db_collation='utf8_general_ci', db_column='Respuesta', max_length=250)),
            ],
            options={
                'db_table': 'empleadoformato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleadoprueba',
            fields=[
                ('idempleadoprueba', models.AutoField(db_column='IdEmpleadoPrueba', primary_key=True, serialize=False)),
                ('codempleado', models.CharField(db_collation='utf8_general_ci', db_column='CodEmpleado', max_length=15)),
            ],
            options={
                'db_table': 'empleadoprueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entradasalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaentradas', models.DateTimeField(db_column='HoraEntradas')),
                ('horasalidas', models.DateTimeField(db_column='HoraSalidas')),
                ('dia', models.DateField(db_column='Dia')),
            ],
            options={
                'db_table': 'entradasalidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista1',
            fields=[
                ('identrevista', models.AutoField(db_column='IdEntrevista', primary_key=True, serialize=False)),
                ('fecharevision', models.DateField(db_column='FechaRevision')),
                ('pasa', models.TextField(db_column='Pasa')),
                ('personaencargada', models.CharField(db_collation='utf8_general_ci', db_column='PersonaEncargada', max_length=35)),
            ],
            options={
                'db_table': 'entrevista1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista2',
            fields=[
                ('identrevista2', models.AutoField(db_column='IdEntrevista2', primary_key=True, serialize=False)),
                ('fecharevision', models.DateField(db_column='FechaRevision')),
                ('pasa', models.TextField(db_column='Pasa')),
                ('personaencargada', models.CharField(db_collation='utf8_general_ci', db_column='PersonaEncargada', max_length=35)),
            ],
            options={
                'db_table': 'entrevista2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadocivil',
            fields=[
                ('idestadocivil', models.AutoField(db_column='IdEstadoCivil', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_collation='utf8_general_ci', db_column='Titulo', max_length=25)),
                ('abreviacion', models.CharField(db_collation='utf8_general_ci', db_column='Abreviacion', max_length=5)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'estadocivil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopostulante',
            fields=[
                ('idestadopostulante', models.AutoField(db_column='IdEstadoPostulante', primary_key=True, serialize=False)),
                ('tipoestado', models.CharField(db_collation='utf8_general_ci', db_column='TipoEstado', max_length=25)),
            ],
            options={
                'db_table': 'estadopostulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiopersona',
            fields=[
                ('idestudio', models.AutoField(db_column='IdEstudio', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafin', models.DateField(db_column='Fechafin')),
            ],
            options={
                'db_table': 'estudiopersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('idexamen', models.AutoField(db_column='IdExamen', primary_key=True, serialize=False)),
                ('nombreexamen', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='NombreExamen', max_length=30, null=True)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'examenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examenpostulante',
            fields=[
                ('idexamenpostulante', models.AutoField(db_column='IdExamenPostulante', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'examenpostulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formatoprueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(db_collation='utf8_general_ci', db_column='Pregunta', max_length=25)),
            ],
            options={
                'db_table': 'formatoprueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionescargo',
            fields=[
                ('idfuncioncargo', models.AutoField(db_column='IdFuncionCargo', primary_key=True, serialize=False)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'funcionescargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidadesempleados',
            fields=[
                ('idhabilidadempleado', models.AutoField(db_column='IdHabilidadEmpleado', primary_key=True, serialize=False)),
                ('porcentajedominio', models.FloatField(db_column='PorcentajeDominio')),
            ],
            options={
                'db_table': 'habilidadesempleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialcargo',
            fields=[
                ('idhistorialcargo', models.AutoField(db_column='IdHistorialCargo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historialcargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiallaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(db_column='Estado')),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafinal', models.DateField(db_column='FechaFinal')),
                ('motivo', models.TextField(db_column='Motivo')),
            ],
            options={
                'db_table': 'historiallaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horariolaboral',
            fields=[
                ('idhorariolaboral', models.AutoField(db_column='IdHorarioLaboral', primary_key=True, serialize=False)),
                ('horaentrada', models.DateTimeField(db_column='HoraEntrada')),
                ('horasalida', models.DateTimeField(db_column='HoraSalida')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'horariolaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horasextra',
            fields=[
                ('idhorasextra', models.AutoField(db_column='IdHorasExtra', primary_key=True, serialize=False)),
                ('cantidadhora', models.FloatField(db_column='CantidadHora')),
                ('pagado', models.FloatField(db_column='Pagado')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('agregadopor', models.CharField(db_collation='utf8_general_ci', db_column='AgregadoPor', max_length=25)),
                ('detalle', models.TextField(db_column='Detalle')),
                ('justificado', models.TextField(db_column='Justificado')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'horasextra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('codidioma', models.CharField(db_collation='utf8_general_ci', db_column='CodIdioma', max_length=5, primary_key=True, serialize=False)),
                ('nombreidioma', models.CharField(db_collation='utf8_general_ci', db_column='NombreIdioma', max_length=15)),
                ('abreviacion', models.CharField(db_collation='utf8_general_ci', db_column='Abreviacion', max_length=5)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'idiomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incentivos',
            fields=[
                ('idincentivo', models.AutoField(db_column='IdIncentivo', primary_key=True, serialize=False)),
                ('pagado', models.FloatField(db_column='Pagado')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('agregadopor', models.CharField(db_collation='utf8_general_ci', db_column='AgregadoPor', max_length=25)),
                ('conceptode', models.TextField(db_column='ConceptoDe')),
                ('justificado', models.TextField(db_column='Justificado')),
            ],
            options={
                'db_table': 'incentivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('idinstrumento', models.AutoField(db_column='IdInstrumento', primary_key=True, serialize=False)),
                ('nombreinstrumento', models.CharField(db_collation='utf8_general_ci', db_column='NombreInstrumento', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'instrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intentossession',
            fields=[
                ('idintentossession', models.AutoField(db_column='IdIntentosSession', primary_key=True, serialize=False)),
                ('numerointentos', models.IntegerField(db_column='NumeroIntentos')),
                ('dispositivo', models.CharField(db_collation='utf8_general_ci', db_column='Dispositivo', max_length=15)),
            ],
            options={
                'db_table': 'intentossession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('idlicencia', models.AutoField(db_column='IdLicencia', primary_key=True, serialize=False)),
                ('categorialicencia', models.CharField(db_collation='utf8_general_ci', db_column='CategoriaLicencia', max_length=20)),
                ('abreviacion', models.CharField(db_collation='utf8_general_ci', db_column='Abreviacion', max_length=5)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llegadastardias',
            fields=[
                ('idllegadatarde', models.AutoField(db_column='IdLlegadaTarde', primary_key=True, serialize=False)),
                ('cantidadhora', models.FloatField(db_column='CantidadHora')),
                ('deducido', models.FloatField(db_column='Deducido')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('agregadopor', models.CharField(db_collation='utf8_general_ci', db_column='AgregadoPor', max_length=25)),
                ('detalle', models.TextField(db_column='Detalle')),
                ('justificado', models.TextField(db_column='Justificado')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'llegadastardias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('idnomina', models.AutoField(db_column='IdNomina', primary_key=True, serialize=False)),
                ('inicioperiodo', models.DateField(db_column='InicioPeriodo')),
                ('finalperiodo', models.DateField(db_column='FinalPeriodo')),
                ('aprobadopor', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='AprobadoPor', max_length=30, null=True)),
                ('elaboradopor', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='ElaboradoPor', max_length=30, null=True)),
                ('totalir', models.FloatField(blank=True, db_column='TotalIR', null=True)),
                ('totalinatec', models.FloatField(blank=True, db_column='TotalInatec', null=True)),
                ('totalinsspatronal', models.FloatField(blank=True, db_column='TotalINSSPatronal', null=True)),
                ('totalinsspersonal', models.FloatField(blank=True, db_column='TotalINSSPersonal', null=True)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'nomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numtelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notelefono', models.CharField(db_collation='utf8_general_ci', db_column='NoTelefono', max_length=20)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'numtelefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paginaweb',
            fields=[
                ('idpaginaweb', models.AutoField(db_column='IdPaginaWeb', primary_key=True, serialize=False)),
                ('url', models.TextField(db_column='URL')),
                ('estado', models.TextField(db_column='Estado')),
                ('descripcion', models.TextField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'paginaweb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paisorigen',
            fields=[
                ('codpais', models.CharField(db_collation='utf8_general_ci', db_column='codPais', max_length=10, primary_key=True, serialize=False)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, max_length=4, null=True)),
                ('nombrepais', models.CharField(db_collation='utf8_general_ci', db_column='NombrePais', max_length=20)),
            ],
            options={
                'db_table': 'paisorigen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('idparentesco', models.AutoField(db_column='IdParentesco', primary_key=True, serialize=False)),
                ('nombreparentesco', models.CharField(db_collation='utf8_general_ci', db_column='NombreParentesco', max_length=30)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodolaboral',
            fields=[
                ('idperiodolaboral', models.AutoField(db_column='IdPeriodoLaboral', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('descripcion', models.CharField(db_collation='utf8_general_ci', db_column='Descripcion', max_length=100)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'periodolaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idpermisos', models.AutoField(db_column='IdPermisos', primary_key=True, serialize=False)),
                ('cantidadhora', models.FloatField(db_column='CantidadHora')),
                ('deducido', models.FloatField(db_column='Deducido')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('agregadopor', models.CharField(db_collation='utf8_general_ci', db_column='AgregadoPor', max_length=25)),
                ('detalle', models.TextField(db_column='Detalle')),
                ('justificado', models.TextField(db_column='Justificado')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisossecurity',
            fields=[
                ('idpermisos', models.AutoField(db_column='IdPermisos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=50)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'permisossecurity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='IdPersona', primary_key=True, serialize=False)),
                ('dui', models.CharField(db_collation='utf8_general_ci', db_column='DUI', max_length=25)),
                ('nombre1', models.CharField(db_collation='utf8_general_ci', db_column='Nombre1', max_length=25)),
                ('nombre2', models.CharField(db_collation='utf8_general_ci', db_column='Nombre2', max_length=25)),
                ('apellido1', models.CharField(db_collation='utf8_general_ci', db_column='Apellido1', max_length=25)),
                ('apellido2', models.CharField(db_collation='utf8_general_ci', db_column='Apellido2', max_length=25)),
                ('fechanac', models.DateField(db_column='FechaNac')),
                ('genero', models.TextField(db_column='Genero')),
                ('nodependientes', models.IntegerField(blank=True, db_column='NoDependientes', null=True)),
                ('foto', models.TextField(blank=True, db_column='Foto', null=True)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaidioma',
            fields=[
                ('idpersonaidioma', models.AutoField(db_column='IdPersonaIdioma', primary_key=True, serialize=False)),
                ('porcentajehablado', models.FloatField(db_column='PorcentajeHablado')),
                ('porcentajeescrito', models.FloatField(db_column='PorcentajeEscrito')),
                ('porcentajeinterpretado', models.FloatField(db_column='PorcentajeInterpretado')),
            ],
            options={
                'db_table': 'personaidioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaredsocial',
            fields=[
                ('idpersonaredsocial', models.AutoField(db_column='IdPersonaRedSocial', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_collation='utf8_general_ci', db_column='NombreUsuario', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'personaredsocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('idpostulante', models.AutoField(db_column='IdPostulante', primary_key=True, serialize=False)),
                ('fechasolicitud', models.DateField(db_column='FechaSolicitud')),
                ('aspiracionsalarial', models.FloatField(db_column='AspiracionSalarial')),
                ('gastomensual', models.FloatField(db_column='GastoMensual')),
                ('montodeudas', models.FloatField(db_column='MontoDeudas')),
                ('cv', models.TextField(db_column='CV')),
                ('registrocompleto', models.TextField(blank=True, db_column='RegistroCompleto', null=True)),
            ],
            options={
                'db_table': 'postulantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedorservicios',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_collation='utf8_general_ci', db_column='NombreProveedor', max_length=25)),
                ('ruc', models.CharField(db_collation='utf8_general_ci', db_column='RUC', max_length=20)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'proveedorservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('idreferencia', models.AutoField(db_column='IdReferencia', primary_key=True, serialize=False)),
                ('anosrelacion', models.FloatField(db_column='AnosRelacion')),
                ('rutadoc', models.TextField(db_column='RutaDoc')),
            ],
            options={
                'db_table': 'referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representacionlegal',
            fields=[
                ('idrepresentante', models.AutoField(db_column='IdRepresentante', primary_key=True, serialize=False)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'representacionlegal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisitoscargo',
            fields=[
                ('idrequisitoscargo', models.AutoField(db_column='IdRequisitosCargo', primary_key=True, serialize=False)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'requisitoscargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revisionoficial',
            fields=[
                ('idrevisionoficial', models.AutoField(db_column='IdRevisionOficial', primary_key=True, serialize=False)),
                ('fecharevision', models.DateField(db_column='FechaRevision')),
                ('pasa', models.TextField(db_column='Pasa')),
                ('personaencargada', models.CharField(db_collation='utf8_general_ci', db_column='PersonaEncargada', max_length=35)),
            ],
            options={
                'db_table': 'revisionoficial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revisionpreliminar',
            fields=[
                ('idrevisionpreliminar', models.AutoField(db_column='IdRevisionPreliminar', primary_key=True, serialize=False)),
                ('fecharevision', models.DateField(db_column='FechaRevision')),
                ('pasa', models.TextField(db_column='Pasa')),
            ],
            options={
                'db_table': 'revisionpreliminar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rolusuario',
            fields=[
                ('idrolusuario', models.AutoField(db_column='idRolUsuario', primary_key=True, serialize=False)),
                ('idcatrol', models.IntegerField(db_column='idCatRol')),
            ],
            options={
                'db_table': 'rolusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tablaprogresiva',
            fields=[
                ('codir', models.CharField(db_collation='utf8_general_ci', db_column='CodIr', max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'tablaprogresiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('codtipocont', models.CharField(db_collation='utf8_general_ci', db_column='CodTipoCont', max_length=8, primary_key=True, serialize=False)),
                ('tipo', models.TextField(db_column='Tipo')),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafinal', models.DateField(db_column='FechaFinal')),
                ('tipojornada', models.CharField(db_collation='utf8_general_ci', db_column='TipoJornada', max_length=25)),
            ],
            options={
                'db_table': 'tipocontrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipofuncion',
            fields=[
                ('idtipofuncion', models.AutoField(db_column='IdTipoFuncion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'tipofuncion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoincentivo',
            fields=[
                ('idtipoincentivo', models.AutoField(db_column='IdTipoIncentivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=20)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'tipoincentivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporequisito',
            fields=[
                ('idrequisito', models.AutoField(db_column='IdRequisito', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'tiporequisito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipovacacion',
            fields=[
                ('idtipovacacion', models.AutoField(db_column='IdTipoVacacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_general_ci', db_column='Nombre', max_length=20)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'tipovacacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('idtitulo', models.AutoField(db_column='IdTitulo', primary_key=True, serialize=False)),
                ('nombretitulo', models.CharField(db_collation='utf8_general_ci', db_column='NombreTitulo', max_length=25)),
                ('abreviacion', models.CharField(db_collation='utf8_general_ci', db_column='Abreviacion', max_length=5)),
                ('relevancia', models.IntegerField(db_column='Relevancia')),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioempleado',
            fields=[
                ('idusuarioemp', models.AutoField(db_column='idUsuarioEmp', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_collation='utf8_general_ci', db_column='Usuario', max_length=100)),
                ('hashpass', models.TextField(db_column='HashPass')),
                ('correoinstitucional', models.TextField(db_column='CorreoInstitucional')),
            ],
            options={
                'db_table': 'usuarioempleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariopostulante',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_collation='utf8_general_ci', db_column='Usuario', max_length=100)),
                ('hashpass', models.TextField(db_column='HashPass')),
                ('correoprop', models.TextField(db_column='CorreoProp')),
            ],
            options={
                'db_table': 'usuariopostulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacacioneacumuladas',
            fields=[
                ('idvacaciones', models.AutoField(db_column='IdVacaciones', primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(db_column='Cantidad')),
                ('pagado', models.FloatField(db_column='Pagado')),
                ('dia', models.DateTimeField(db_column='Dia')),
                ('agregadopor', models.CharField(db_collation='utf8_general_ci', db_column='AgregadoPor', max_length=25)),
                ('detalle', models.TextField(db_column='Detalle')),
                ('justificado', models.TextField(db_column='Justificado')),
            ],
            options={
                'db_table': 'vacacioneacumuladas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('codvacante', models.CharField(db_collation='utf8_general_ci', db_column='CodVacante', max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='utf8_general_ci', db_column='Descripcion', max_length=100)),
                ('presupuestopublicidad', models.FloatField(db_column='PresupuestoPublicidad')),
                ('fechalimiterecepcion', models.DateField(db_column='FechaLimiteRecepcion')),
                ('fechacontratacion', models.DateField(db_column='FechaContratacion')),
                ('fechaelaboracion', models.DateField(db_column='FechaElaboracion')),
                ('elaboradapor', models.CharField(db_collation='utf8_general_ci', db_column='ElaboradaPor', max_length=25)),
                ('autorizadapor', models.CharField(db_collation='utf8_general_ci', db_column='AutorizadaPor', max_length=25)),
                ('estado', models.TextField(db_column='Estado')),
            ],
            options={
                'db_table': 'vacante',
                'managed': False,
            },
        ),
    ]
