# Generated by Django 3.2.9 on 2021-11-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20211124_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrols',
            options={'managed': False, 'permissions': (('ResponsableDivisióndeRecursosHumanos', 'Responsable División de Recursos Humanos'), ('movimientoPersonal', 'Responsable Oficina de Desarrollo'), ('recursosLaborales', 'Analista de Recursos Laborales'), ('responsableNomina', 'Responsable Oficina de Nómina'), ('evaluacionDesempeño', 'Responsable de Relaciones Laborales'))},
        ),
    ]
